language: java
jdk:
   - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
cache:
  directories:
   - $HOME/.m2

sudo: false
dist: trusty

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "jvl9/8MXP1biijN01Sbp48/Plg+iLMpdGcb4WUs0YnguD8hLALJ/GpR8YpWcMxYJe660i3Aao/6G82NgP6er6z10vWuoicuwmJs7UxBg0l+hlo32tGoRX9XvzvVaORRbrwimdDeEwJX+NBnus8Tv06bzHjXABSMLhpNfZP0LVqAEzpkflxLMDdOiSxbTDNkXecmiqqCKX1aWszuH6Blhhxo0AzP0tg8MDb+gZTVwSYM1lh0gsz/o4N3FfpgVVBoAsdSl3Ji6HiALPw5NpAK/hJB+KgHjJsSqlSERr5P4vkFIvtvzyUzTcKj1Op9Bs9CNaBVhbX316jmReYzvy46DuJn/8XMM+luo2sCxVxiSrsM5ggAb2OLnbKHXDktB5vePK4vF5lZb7NkALbhK2Jz5HhE1I5M4ax3EocWIRTiCBJDSi0KHlbRxDoXq74iPHWKlCnXOTmZ/fhZG7UvD2eH8rccvvgJ7HEJk3yUVJedbiFC772W49JaeDl4Tw2iiWKhBI+s8tW4wufkWBaPgC3Vvk4WS1A4O/wYNEtEYUWG1tO8Zb4RdYPMCZ+DvK9kn8DFjCmKcMEQe4awgDL3ihMLbWsFCxZulzhJRbWpsadkmKLGMGU0x9LBgLugIxKSO0Wdi1CTNpO0uKIWnki+ariD2X40FbyqSjLZseeNtFA9PHbE="
  
addons:
  coverity_scan:
    project:
      name: "jnidzwetzki/bitfinex-v2-wss-api-java"
      description: "Build submitted via Travis CI"
    notification_email: jnidzwetzki@gmx.de
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

